version: "3"

services:
  mongo:
    image: mongo
    container_name: cyrius-mongo
    ports:
    - 27017:27017

  rabbit:
    hostname: rabbit
    container_name: cyrius-rabbit
    tty: true
    build:
      context: .
      dockerfile: rabbit-dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    ports:
    - 5672:5672
    - 15672:15672
